package org.emil.hnrpmc.hnessentials.cosmetics.api;


import org.emil.hnrpmc.hnessentials.cosmetics.impl.CosmeticFetcher;
import org.jetbrains.annotations.Nullable;

/**
 * Represents the data of a cape served by the cosmetica servers.
 */
public interface Cape {
    /**
     * @return the id of this cape.
     * @apiNote If not a cosmetica cape, an ID using a format which cannot conflict with cosmetica's will be generated by the server on the fly using the player UUID and timestamp, so cannot be guaranteed to be the same every time.
     */
    String getId();

    /**
     * Gets the cosmetic server this originates from.
     * @return the origin of this cape. Whether it be "Cosmetica" or "Optifine," etc...
     */
    String getOrigin();

    /**
     * Get the cape base64 image string. May be different dimensions depending on how many frames it has. Each frame has a 2:1 width:height aspect ratio and they stack vertically.
     * @return the image, in base64 format
     */
    String getImage();

    /**
     * @return the delay between each frame of this cape, in ms. Will be 0 if static.
     */
    int getFrameDelay();

    /**
     * @return whether this cape is an animated cape.
     */
    default boolean isAnimated() {
        return this.getFrameDelay() > 0;
    }

    /**
     * @return the name of this cape. May be blank if cosmetica cannot get the name from the cape server whence it originates.
     */
    String getName();

    /**
     * @return whether the user's cape, if from an alternative cape server, has been replaced with a cosmetica cape, in accordance with the cape settings of the token this cape was obtained with.
     */
    boolean isCosmeticaAlternative();

    /**
     * Makes an api request to fetch cape data from cosmetica.
     * @param id the id of the cape to request
     * @return an object containing information on the cape. Null if there is no cape for the given id.
     */
    @Nullable
    static CustomCape fetch(String id) {
        return CosmeticFetcher.getCape(id);
    }
}
